SELECT 
    YEAR,
    MONTH,
    COUNT(DISTINCT A.USER_ID) PUCHASED_USERS,
    ROUND(COUNT(DISTINCT A.USER_ID)/CNT,1) PUCHASED_RATIO
FROM
    (SELECT 
        USER_ID, 
        YEAR(SALES_DATE) YEAR, 
        MONTH(SALES_DATE) MONTH 
     FROM ONLINE_SALE 
     GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_ID) A
    LEFT JOIN
    (SELECT 
        USER_ID, 
        (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED)="2021" GROUP BY YEAR(JOINED)) CNT 
     FROM USER_INFO WHERE YEAR(JOINED)="2021") B
    ON A.USER_ID=B.USER_ID
WHERE B.USER_ID IS NOT NULL
GROUP BY YEAR, MONTH